directories:
  output: uninstaller-dist
  buildResources: build
appId: com.infernoconsole.uninstaller
productName: Inferno Console Uninstaller
files:
  - filter:
      - main-uninstaller.js
      - index.html
      - style.css
      - script.js
win:
  target: portable
  icon: assets/icon.ico
portable:
  artifactName: Inferno-Console-Uninstaller.exe
electronVersion: 28.3.3
