name: Build

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run lint

    - name: Build application
      run: npm run build

    - name: Test build (Windows)
      if: matrix.os == 'windows-latest'
      run: npm run dist:win:nsis

    - name: Test build (macOS)
      if: matrix.os == 'macos-latest'
      run: npm run dist
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Test build (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: npm run dist:all

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: dist-electron/
        retention-days: 7
